server:
  port: 8080

spring:
  profiles:
    active: 
    - local #local dev pru pro
  application:
    name: servicios-activos-fijos
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true 
        dialect : org.hibernate.dialect.Oracle12cDialect
    generate-ddl : true 
    hibernate:
      ddl-auto: update
            
  datasource:
    url: jdbc:oracle:thin:@10.20.102.118:12003/SIMELDES
    username: SIMEL_APP
    password: S1m3lDES 
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    driver-class-name: oracle.jdbc.OracleDriver
  main:
    allow-bean-definition-overriding: true

name: local-YAML      
environment: local
enabled: true   